### ISSUE TITLE
gulpfile unexpected token

### ISSUE THREAD

**Issue by mixcas** [interglobalvision/interglobalvision-wp-boil#14]
missing parentheses on gulpfile.js L46, thanks @varffs

**Comment by varffs** [comment]
is this really worth an issue? cant u just fix it? lol

**Comment by mixcas** [comment]
yes i could
![u mad](http://img2.wikia.nocookie.net/__cb20140912213621/t-r-o-t-c/images/0/0c/Mexican_troll_face_by_mariodude12312-d5mtl9z.png)

i wanna practice issues tho, i just discovered u can't put a reference to a specific line of a file :(

**Comment by varffs** [comment]
how upsetting
