### ISSUE TITLE
jslint or jshint?

### ISSUE THREAD

**Issue by varffs** [interglobalvision/interglobalvision-wp-boil#17]
jslint requires 4 space indentation otherwise we cant check for spacing at all! maybe we should use jshint or do we need to start using 4 space indents?

**Comment by varffs** [comment]
hmm so found out I'm wrong about this. But perhaps raises the question of do we defint jslint options in .js files or in the gulpfile?

**Comment by mixcas** [comment]
u can set the indentation size
check https://github.com/interglobalvision/interglobalvision-wp-boil/blob/master/js/main.js 1:2
add it to ur code

**Comment by varffs** [comment]
yeah thats what I found out. I set it in the gulpfile hence the second question

**Comment by mixcas** [comment]
i think we should set on file basis tis more flexible
