### ISSUE TITLE
move into the future, ES2015

### ISSUE THREAD

**Issue by mixcas** [interglobalvision/interglobalvision-wp-boil#38]
https://atmospherejs.com/meteor/ecmascript

**Comment by varffs** [comment]
I think you meant to put this in the meteor boil?

**Comment by varffs** [comment]
@mixcas ^^^

**Comment by mixcas** [comment]
no, first check if it already is there cuz i think the newest meteor version has it by default
then  rewrite the whole boilerplate with ES2015

**Comment by mixcas** [comment]
lol wrong boilerplate
