### ISSUE TITLE
V 2.0

### ISSUE THREAD

**Issue by mixcas** [interglobalvision/interglobalvision-wp-boil#56]
I guess is time to write v 2.0 of the boilerplate. We should think about what to keep, refactor or add.

This are the things I would like in this version:

- Setup script. To setup repo and install dependencies
- Refactor grid, both fluid and fixed widths, in a way we all can agree to and also as a [mixin](http://stylus-lang.com/docs/mixins.html). I advocate for the use of flex. I believe we can make a flex grid which work for fluid and fixed width.
- Better package management, for plugins and dependencies
- Better utility classes, as mixins, for margins, borders and stuff
- Better site options page, with options to add more than one options page
- ES6 support.
- Test page, a plain HTML page that has examples of code that display grid, margins, utility classes, etc by examples. This will be useful to test changes and improvements to the boilerplate. It works as well as documentation.

I think we should also consider on looking at frameworks like Bootstrap, Foundation or Semantic to learn how they manage their code, media-queries, best practices, etc.

If you have more ideas comment them, I'll add them to the list.

**Comment by varffs** [comment]
I 100% agree with all of this. Also to be explicit we should move to composer for php package management. And possibly bower or similar for js dependencies

**Comment by varffs** [comment]
Yeah i think we should incorporate bower with gulp to generate our library.js file: https://github.com/ck86/main-bower-files

**Comment by varffs** [comment]
Also we should call the project and repo something better

**Comment by mixcas** [comment]
@varffs Composer seems perfect for CMB2 intergation.

I don't understand what could we use bower for. What packages have we use/could use from bower in our projects?

**Comment by varffs** [comment]
js libs like Swiper, ImagesLoaded, Masonry etc

**Comment by mixcas** [comment]
ohh true, we use those a lot. good point.

**Comment by varffs** [comment]
I'm wondering if we could have a cheat sheet(s) for common code that we often use in projects but not nec every project. For example when I use Moment PHP for localized date formatting setting the locale needs to be done and that code for this is always the same. Same for other qtranslate-x snippets. Etc. We could have a folder of these cheat sheets in the boiler (we could also do them in another repo but makes sense here to me)

**Comment by varffs** [comment]
make this into milestone. add issues for things outstanding and assign them
